# Project Details
sonar.projectKey=task-management-system
sonar.projectName=Task Management System

# Root directory
sonar.sources=.

# Include source code for Backend & Frontend
sonar.inclusions=backend/src/main/java/**,task-management-system-frontend/src/**

# Exclude non-production source files that ARE pushed to Git
sonar.exclusions=**/*.test.js,**/*.spec.ts,**/*Test.java,**/mvnw*,**/Dockerfile
